

server:
  port: 8181

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/test
    username: choyejin
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    # show-sql: true  # 자동 생성된 쿼리를 보여주는 옵션
    # 로그가 나올 때 어떤 디비에 맞게 나오는지 설정
    database-platform: org.hibernate.dialect.MariaDB106Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true # sql을 줄바꿈해서 이쁘게 출력
    database: mysql # 디비 계열 설정
  servlet:
    multipart:
      max-file-size: 10MB # 1개의 파일의 최대 사이즈
      max-request-size: 20MB # 전체 요청의 최대 사이즈


logging.level:
  org.hibernate.SQL: debug

# swagger setting
springdoc:
  swagger-ui:
    path: /myapi.html


jwt:
  secret: be6GWIs0VIxkrZ/mLkzEyjNX94okeN7+hV+7/yXIGLdveoQfVFTtDHg0iDTsK89WO1mRgigV/Z27zwieRP9OBQ==

# 업로드파일 저장 경로
upload:
  path: /Users/choyejin/todo-upload

#s3 접근 설정
aws:
  credentials:
    accessKey: AKIAWFGAQ3PXANPDGGMT #복사해서 받은 키 붙여넣기
    secretKey: 2eJm4HpRHYxXkvuOuTQdqdi8asyUgdO2vQScUKb1
  region: ap-northeast-2
  bucketName: file-upload-bucket9984